/**
 * Created by Alan on 2017/6/5.
 */

export const SEND_REQUEST = 'SEND_REQUEST'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILURE = 'REQUEST_SUCCESS'
export const RECEIVE_TECHLIST = 'RECEIVE_TECHLIST'
export const RECEIVE_TECH = 'RECEIVE_TECH'
export const TOGGLE_TECH_DETAIL = 'TOGGLE_TECH_DETAIL'
export const SELECT_TECHNICIAN = 'SELECT_TECHNICIAN'
